namespace UniversityEquipmentRentalService;

public class Equipment
{
    //The name of the equipment
    public string name;
    
    //Serial number - generated by the system
    public string serialNumber;

    //Status of the equipment determining the rent possibility
    public enum status
    {
        Available,
        Unavailable,
        Damaged,
        Maintaining
    }
    
    //Information about Manufacturer
    public string manufacturer;
    
    //Information about insurance value
    public int insurance;
}