using System.Reflection.PortableExecutable;

namespace UniversityEquipmentRentalService;

public class Equipment
{
    //The name of the equipment
    public string name;
    
    //Serial number - generated by the system
    public string serialNumber;

    //Status of the equipment determining the rent possibility
    public enum status
    {
        Available,
        Unavailable,
        Damaged,
        Maintaining
    }
    
    //Information about Manufacturer
    public string manufacturer;
    
    //Information about insurance value
    public int insurance;
    
    //Filed used to generate Serial number
    protected static int index = 0;

    protected virtual string generateSerialNumber()
    {
        index++;
        index.ToString("D5");
        string prefix = "VD";
        
        return prefix + index;
    }

    public Equipment(string name, string manufacturer, int insurance)
    {
        this.name = name;
        this.manufacturer = manufacturer;
        this.insurance = insurance;
        this.serialNumber = generateSerialNumber();
    }

    public void displayInfo()
    {
        Console.WriteLine("Equipment Information:");
        Console.WriteLine("Name: " + name);
        Console.WriteLine("Serial Number: " + serialNumber);
        Console.WriteLine("Manufacturer: " + manufacturer);
        Console.WriteLine("Insurance Value: " + insurance);
    }
}